/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.ufpe.cin.residencia.stellantis.gradle.actions;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void soma() {
        int x = 3;
        int y = 5;
        assertEquals(8, App.soma(x, y), "Soma de 3 e 5 deveria ser 8");        
    }

    @Test void resultadoSoma() {
        int x = 3;
        int y = 5;
        assertEquals("3 + 5 = 8", App.resultadoSoma(x, y), "Mensagem esta diferente");        
    }

    @Test void multiplicacao() {
        int x = 3;
        int y = 5;
        assertEquals(15, App.multiplicacao(x, y), "Multiplicacao de 3 e 5 deveria ser 15");        
    }

    @Test void subtracao() {
        int x = 5;
        int y = 3;
        assertEquals(2, App.subtracao(x, y), "Subtracao de 5 e 3 deveria ser 2");        
    }

    @Test void divisao() {
        int x = 10;
        int y = 5;
        assertEquals(2, App.divisao(x, y), "Divisao de 10 por 5 deveria ser 2");
    }

}
