/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.ufpe.cin.residencia.stellantis.gradle.actions;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void soma() {
        int x = 3;
        int y = 5;
        assertEquals(8, App.soma(x, y), "Soma de 3 e 5 deveria ser 8");        
    }

    @Test void multiplicacao() {
        int x = 3;
        int y = 5;
        assertEquals(15, App.multiplicacao(x, y), "Multiplicação de 3 e 5 deveria ser 15");        
    }
}
