/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.ufpe.cin.residencia.stellantis.gradle.actions;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static int soma(int a, int b) { 
        return a + b;
    }

    public static int multiplicacao(int a, int b) { 
        return a * b;
    }

    public static int subtracao(int a, int b) { 
        return a - b;
    }

    public static int divisao(int a, int b) { 
        if (b!=0) { 
            return a/b;
        }
        else { 
            throw new RuntimeException("Divisao por zero!");
        }
    }
    
    public static String resultadoSoma(int a, int b) { 
        StringBuilder sb = new StringBuilder();
        //" a + b = resultado(a+b)"
        //" 2 + 3 = 5"
        sb.append(a);
        sb.append(" + ");
        sb.append(b);
        sb.append(" = "); 
        sb.append(soma(a,b));
        return sb.toString();
    }

    public static String resultadoSubtracao(int a, int b) { 
        StringBuilder sb = new StringBuilder();
        sb.append(a);
        sb.append(" - ");
        sb.append(b);
        sb.append(" = "); 
        sb.append(subtracao(a,b));
        return sb.toString();
    }

    public static String resultadoMultiplicacao(int a, int b) { 
        StringBuilder sb = new StringBuilder();
        sb.append(a);
        sb.append(" * ");
        sb.append(b);
        sb.append(" = "); 
        sb.append(multiplicacao(a,b));
        return sb.toString();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(resultadoSoma(3,5));
    }
}
